# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Azure for Students(36000fc5-3a82-4990-9709-6a571fb9219e)'
    Action: 'Stop Azure App Service'
    WebAppName: 'MI1HP3'
    SpecifySlotOrASE: true
    ResourceGroupName: 'MI1_Development_B1_Plan'
    Slot: 'production'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    downloadPath: '$(System.ArtifactsDirectory)'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(36000fc5-3a82-4990-9709-6a571fb9219e)'
    appType: 'webAppLinux'
    WebAppName: 'MI1HP3'
    deployToSlotOrASE: true
    ResourceGroupName: 'MI1_Development_B1_Plan'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|16-lts'
    StartupCommand: 'npm run build'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Azure for Students(36000fc5-3a82-4990-9709-6a571fb9219e)'
    Action: 'Start Azure App Service'
    WebAppName: 'MI1HP3'
    SpecifySlotOrASE: true
    ResourceGroupName: 'MI1_Development_B1_Plan'
    Slot: 'production'